### ISSUE TITLE
Release 2.0

### ISSUE THREAD

**Issue by parente** [jupyter/kernel_gateway#242]
Let's discuss making a 2.0 release. Here's things I think need to get done vs those that can be moved out:

TODOs

* [x] Come to resolution on #236, do we need to update the swagger more or not?
* [x] Move #211 out to a 2.1 or 3.0 release. KG has support for tokens in query parameters now. This issue is to switch to using the implementation in jupyter/notebook instead of the custom one here if it's possible and makes sense to do so.
* [x] Improve description in the doc for #229  (PR #246)
* [x] Test a couple of https://github.com/jupyter/kernel_gateway_demos to ensure they are still functional with the changes in master
* [x] Update the changelog both in the project root and doc

What do folks think? @rolweber?

**Comment by rolweber** [comment]
For a major release, we should consider #229 as well.

**Comment by parente** [comment]
Fine by me. I'll tag it 2.0. Are you cool with moving #211 out of the 2.0 milestone?

**Comment by rolweber** [comment]
Yes, that's fine with me.

**Comment by rolweber** [comment]
How much extra effort would it be to release 1.2.2 alongside 2.0?
How could I help? Update the changelog in both branches?

**Comment by parente** [comment]
It's not too much effort. I'm happy to do it. I'll send PRs for that branch. I think there's a backport missing for a duplicate deserialization bug fix that has to go into that branch too.

**Comment by parente** [comment]
@rolweber I tagged and pushed 1.2.2 off the 1.2.x branch. It should be on pypi. Do you also need a conda-forge package built for it? I haven't done multi-branch conda-forge builds, but I hear it's possible by creating branches in https://github.com/conda-forge/jupyter_kernel_gateway-feedstock

**Comment by rolweber** [comment]
@parente: Great, thanks! PyPI is sufficient for now.

One small nuisance though: PyPi now considers 1.2.2 to be the "latest version".
https://pypi.python.org/pypi/jupyter_kernel_gateway/2.0.0

**Comment by parente** [comment]
Ah. I can fix that. I can also grant you permission to manage it if you'd like. Create an account on pypi and let me know your username if you are interested.

**Comment by rolweber** [comment]
@parente: Great, thanks! I registered at PyPI as 'rolweber'.

**Comment by parente** [comment]
@rolweber I've added you as a maintainer on pypi. One of these days when we cut a new release, I can take you through the steps if you're available.
